"""add status column to users

Revision ID: 2469f349ae26
Revises: 97b915d1aaa5
Create Date: 2025-07-23 05:37:49.893215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2469f349ae26'
down_revision: Union[str, Sequence[str], None] = '97b915d1aaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('status', sa.String(length=50), server_default='pending'))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'status')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
