"""create invite table

Revision ID: d279f1e03118
Revises: 
Create Date: 2025-07-23 03:44:50.337420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd279f1e03118'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badges')
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('videos', 'keypoints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.alter_column('workout_logs', 'keypoints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_workout_logs_id'), 'workout_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_id'), table_name='workout_logs')
    op.alter_column('workout_logs', 'keypoints',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.alter_column('videos', 'keypoints',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.create_table('badges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('earned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('badges_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('badges_pkey'))
    )
    # ### end Alembic commands ###
